function [ P, tri ] = getTetrahedralMesh()
	P = [ ...
		1 1 1 ; ...
		1 -1 -1 ; ...
		-1 1 -1 ; ...
		-1 -1 1   ...
	]';
	P = P ./ repmat( sqrt( sum( P.^2 ) ), 3, 1 );
	P = P - repmat( mean( P, 2 ), 1, size( P, 2 ) );
	P = randomlyRotate( P );
	tri = [ ...
		1 2 3 ; ...
		4 2 1 ; ...
		1 3 4 ; ...
		4 3 2   ...
	];
end
